import sanitizeHtml from "sanitize-html";

export function sanitizeContent(html: string): string {
  if (!html) return "";

  return sanitizeHtml(html, {
    allowedTags: [
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "p",
      "b",
      "i",
      "strong",
      "em",
      "u",
      "strike",
      "a",
      "ul",
      "ol",
      "li",
      "blockquote",
      "hr",
      "img",
      "figure",
      "figcaption",
      "div",
      "span",
      "br",
    ],
    allowedAttributes: {
      a: ["href", "name", "target", "rel", "class"],
      img: ["src", "alt", "title", "width", "height", "class", "loading"],
      div: ["class", "id", "data-*"],
      span: ["class", "id"],
      h2: ["id", "class"],
      h3: ["id", "class"],
      h4: ["id", "class"],
      p: ["class"],
      figure: ["class"],
      figcaption: ["class"],
      blockquote: ["class"],
    },
    allowedClasses: {
      "*": [
        "custom-callout",
        "callout-kicker",
        "custom-problem-grid",
        "custom-problem-card",
        "problem-num",
        "custom-checklist",
        "custom-checklist-item",
        "checklist-num",
        "checklist-body",
        "custom-feature-panel",
        "feature-grid",
        "feature-item",
        "feature-icon",
        "feature-highlight",
        "rich-figure",
        "drop-cap",
        "inline-flex",
        "items-center",
        "justify-center",
        "w-7",
        "h-7",
        "bg-marigold",
        "text-ink",
        "text-xs",
        "font-bold",
        "rounded-full",
        "mr-2",
      ],
    },
  });
}
